# Generated by Django 4.2.5 on 2023-09-15 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_question_correct_answer_question_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='SurveyResponse',
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Survey.survey'),
        ),
    ]
