# Generated by Django 4.2.5 on 2023-09-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0005_question_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
